<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS4ZYVJc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS4ZYVJc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS4ZYVJc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS4ZYVJc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS4ZYVJc\App_KernelDevDebugContainer([
    'container.build_hash' => 'S4ZYVJc',
    'container.build_id' => '531f0b23',
    'container.build_time' => 1701787500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS4ZYVJc');
