<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5P6VXd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5P6VXd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5P6VXd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5P6VXd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA5P6VXd\App_KernelDevDebugContainer([
    'container.build_hash' => 'A5P6VXd',
    'container.build_id' => '0f98e550',
    'container.build_time' => 1703174797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5P6VXd');
